### ISSUE TITLE
Feature: Implement WSD scheduler

### ISSUE THREAD

**Issue by casper-hansen** [euclaise/supertrainer2000#1]
Hi @euclaise, could it be relevant to implement this learning rate scheduler for optimal learning during training?

the OpenBMB team trained a 2.4B model that gets close to Mistral 7B and exceeds L2 13B

https://shengdinghu.notion.site/MiniCPM-Unveiling-the-Potential-of-End-side-Large-Language-Models-d4d3a8c426424654a4e80e42a711cb20

**Comment by euclaise** [comment]
Will do.

https://github.com/euclaise/supertrainer2000/issues/2
