### ISSUE TITLE
Adalite v2 not implemented properly 

### ISSUE THREAD

**Issue by IsNoobgrammer** [euclaise/supertrainer2000#6]
Hello while testing and comparing with other optimizers 
adalite is currenlty not implemented properly 

from what i can see there seems to be a typo in [L51](https://github.com/euclaise/supertrainer2000/blob/master/src/supertrainer2k/optim/adalite.py#L51) where it should be grad.reshape i guess..

**Comment by euclaise** [comment]
Good catch! I didn't notice, as my test models didn't have any >2D parameter tensors. 

Thank you! Will fix when I get on my laptop

**Comment by IsNoobgrammer** [comment]
Even after correcting typo, while testing it on CNN it results in error due to  mismatched dimensions

![image](https://github.com/euclaise/supertrainer2000/assets/112808251/24073108-75c0-4d65-bc3f-de2bf92c9e1d)

**Comment by euclaise** [comment]
> Even after correcting typo, while testing it on CNN it results in error due to  mismatched dimensions
> 
> ![image](https://github.com/euclaise/supertrainer2000/assets/112808251/24073108-75c0-4d65-bc3f-de2bf92c9e1d)
> 

Yep, missing another reshape at the end. Gimme 45min

**Comment by euclaise** [comment]
Should work now

**Comment by IsNoobgrammer** [comment]
> Should work now

Yep, Thanks

**Comment by IsNoobgrammer** [comment]
![image](https://github.com/euclaise/supertrainer2000/assets/112808251/b61e0b52-c782-4944-a648-2afdb39c65b7)

I have tried to implement a simple Optimizer What are your thoughts on this ..
